/**
 * Regression tests for defects in scripts/audit-colors.ts as shipped at
 * commit 7b9c09e.
 *
 * These tests describe the CORRECT behavior of the parser / classifier / CLI
 * boundary. Written against 7b9c09e they were RED, one failure per concrete
 * defect; the working tree carries the scanner fix that turns them green, and
 * each test pins one defect so it cannot quietly come back:
 *
 *   1. Position tracking — ordinary "\n" characters never advanced the line
 *      counter (only strings/comments/url bodies went through `track`), so a
 *      report generated by 7b9c09e attributed every occurrence to line 1 with
 *      an accumulated column — 20,635 of 20,635 rows misattributed.
 *   2. Color heuristic — `line` in COLORISH_NAME made non-color tokens like
 *      the real `--orb-*-line-height: var(--orb-typo-...)` definitions
 *      inventory as color redefinitions (~900 rows in the 7b9c09e report).
 *   3. CSS idents — var() name capture uses ASCII-only regexes; CSS idents
 *      allow any code point >= U+0080, so `--brand-цвет` is truncated to
 *      `--brand-` and `--цвет-1` degrades to the whole `var(...)` call text.
 *   4. Classifier — every custom-property definition is prescribed the
 *      `token-redefinition` override (a :root/.theme_dark emission). For a
 *      component-scoped definition the element's own declaration always beats
 *      an inherited :root value, so that advice cannot win the cascade.
 *   5. Scanner — the unquoted-url mask in the main loop can never fire (its
 *      guard requires the buffer to already end with "url(" before the "(" is
 *      examined), so `;` or `{`/`}` inside a spec-valid unquoted url token
 *      splits declarations / corrupts rule frames.
 *   6. CLI — `--out` happily resolves to the pinned input asset; running with
 *      it would overwrite the SHA-256-pinned evidence file the script promises
 *      to treat read-only.
 *   7. Report facts — the hardcoded svg-dom note claims "one masked url()
 *      fill"; the pinned asset contains six url() paint references and they
 *      are not masked. The note must not misstate the asset.
 *
 * The reports/ inventory in the tree was regenerated by the fixed scanner, so
 * the whole suite — controls included — is expected to pass; any failure here
 * means a pinned defect was reintroduced. The controls additionally pin
 * neighboring behavior the fix must not break (real line colors stay
 * inventoried, :root definitions keep the token-redefinition override,
 * ordinary --out works).
 *
 * Run: bun test tests/audit-colors.test.ts
 */

import { describe, expect, test } from "bun:test"
import { readFile, rm } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join, resolve } from "node:path"
import { ASSET_RELATIVE, parseArgs, parseStylesheet, ROOT } from "../scripts/audit-colors"

type ScanResult = ReturnType<typeof parseStylesheet>
type Occurrence = ScanResult["occurrences"][number]

/** Fails with the inventoried property list when an expected occurrence is absent. */
function mustFind(result: ScanResult, property: string): Occurrence {
  const found = result.occurrences.find((o) => o.property === property)
  if (!found) {
    const inventoried = result.occurrences.map((o) => o.property).join(", ") || "(none)"
    throw new Error(`expected a color-bearing occurrence for "${property}"; inventoried: ${inventoried}`)
  }
  return found
}

describe("parseStylesheet: position tracking", () => {
  test("declarations report accurate line and intra-line column across ordinary newlines", () => {
    // Contract: occurrence.line/column point at the declaration's first
    // non-whitespace character, 1-based. The newline characters here are
    // ordinary content — not inside strings, comments, or url() bodies.
    const css = [":root {", "  --brand-accent: #ff0000;", "  color: green;", "}", "", ".x { border-color: blue; }"].join("\n")
    const result = parseStylesheet(css)

    // Pinned defect: unfixed, every occurrence reported line 1 with the
    // column accumulated across all preceding newlines (e.g. --brand-accent
    // at line 1, col 11).
    expect(mustFind(result, "--brand-accent")).toMatchObject({ line: 2, column: 3 })
    expect(mustFind(result, "color")).toMatchObject({ line: 3, column: 3 })
    expect(mustFind(result, "border-color")).toMatchObject({ line: 6, column: 6 })
  })
})

describe("custom-property color heuristic", () => {
  test("non-color --orb-*-line-height definitions are not inventoried as colors", () => {
    // Real shapes from the pinned asset: the typography ramp stores line
    // heights under color-family-looking names and references other numeric
    // tokens. Unfixed, "line" in COLORISH_NAME pulled the var()-valued ones
    // into the inventory as color redefinitions (~900 rows in the 7b9c09e
    // report).
    const css = ":root{--orb-heading-xl-line-height:var(--orb-typo-heading-line-height-xl);--orb-typo-heading-line-height-xl:40px}"
    const result = parseStylesheet(css)
    const properties = result.occurrences.map((o) => o.property)

    expect(properties).not.toContain("--orb-heading-xl-line-height")
    // Control (already true today): numeric-valued line-height stays excluded.
    expect(properties).not.toContain("--orb-typo-heading-line-height-xl")
  })

  test("control: genuine line colors like --orb-line-brand stay color-bearing", () => {
    // Guarding the fix's blast radius: --orb-line-* tokens ARE colors (the
    // divider/line ramp; in the pinned asset they live in :root and alias
    // --orb-color-* ramps), so excluding line-height names must not exclude
    // these. Root-scoped, so token-redefinition remains the right override.
    const result = parseStylesheet(":root{--orb-line-brand:#1a73e8}")
    expect(mustFind(result, "--orb-line-brand")).toMatchObject({ kind: "token-definition", override: "token-redefinition" })
  })
})

describe("custom property names are CSS idents", () => {
  test("var() name with a non-ASCII tail is captured exactly, not truncated to ASCII", () => {
    // CSS idents allow any code point >= U+0080. The 7b9c09e capture regex
    // (--[a-zA-Z0-9-]+) stopped at the first non-ASCII char, recording the
    // truncated name "--brand-" instead of the referenced property name; the
    // assertion pins the exact capture.
    const result = parseStylesheet(".a{color:var(--brand-цвет)}")
    const token = mustFind(result, "color").tokens[0]
    expect(token?.type).toBe("var")
    expect(token?.name).toBe("--brand-цвет")
    // Control: source classification must stay component-token after the fix.
    expect(mustFind(result, "color").sources).toEqual(["component-token"])
  })

  test("var() name starting with a non-ASCII character does not degrade to the whole call text", () => {
    // With no ASCII ident chars after "--", the 7b9c09e capture failed
    // entirely and recorded the full "var(--цвет-1)" call as the name, which
    // also poisoned aggregation keys and source classification inputs.
    const result = parseStylesheet(".a{color:var(--цвет-1)}")
    const token = mustFind(result, "color").tokens[0]
    expect(token?.type).toBe("var")
    expect(token?.name).toBe("--цвет-1")
  })
})

describe("override method applicability", () => {
  test("component-scoped token definitions are not prescribed a :root redefinition", () => {
    // OVERRIDE_METHODS["token-redefinition"] emits on :root/.theme_dark. A
    // custom property declared on the component element itself always wins
    // over an inherited :root value, so for component-scoped definitions that
    // method cannot recolor anything and must not be prescribed.
    const insideRule = ".yamb-chat-action{--component-compose-accent:var(--orb-color-red-3)}"
    const insideMedia = "@media (min-width: 600px){.yamb-chat-action{--component-compose-accent:var(--orb-color-red-3)}}"

    for (const css of [insideRule, insideMedia]) {
      const result = parseStylesheet(css)
      const occurrence = mustFind(result, "--component-compose-accent")
      // The kind (a token definition) is fine; only the prescribed method is wrong.
      expect(occurrence.kind).toBe("token-definition")
      expect(occurrence.override).not.toBe("token-redefinition")
    }
  })

  test("control: :root-scoped definitions keep the token-redefinition override", () => {
    // :root CAN win for root-scoped definitions (appended-last injected sheet,
    // equal specificity) — the fix must not take this legitimate case away.
    const result = parseStylesheet(":root{--component-compose-accent:var(--orb-color-red-3)}")
    expect(mustFind(result, "--component-compose-accent").override).toBe("token-redefinition")
  })
})

describe("declaration scanning around unquoted url()", () => {
  test("semicolon inside an unquoted url() does not split the declaration stream", () => {
    // data: URIs carry ";" legally inside the url token (e.g. ;base64,).
    // Unfixed, the stream-level mask never fired, so the ";" terminated the
    // declaration early and the remainder became a junk ";-fragment".
    const css = ".a{background-image:url(data:image/svg+xml;base64,PHN2Zy8+);border-color:#123456}"
    const result = parseStylesheet(css)

    expect(result.skippedFragments).toBe(0)
    // The declaration after the url() must survive with intact boundaries.
    expect(mustFind(result, "border-color")).toMatchObject({ selector: ".a", value: "#123456" })
  })

  test("braces inside an unquoted url() do not corrupt the rule context", () => {
    // "{" and "}" are legal url code points. Unfixed, "{" opened a bogus rule
    // frame whose prelude was the half-swallowed declaration, so the next
    // declaration's selector was that garbage instead of ".a".
    const css = ".a{background-image:url(data:image/svg+xml,<svg{>);border-color:#123456}.b{color:#040506}"
    const result = parseStylesheet(css)

    expect(mustFind(result, "border-color")).toMatchObject({ selector: ".a", value: "#123456" })
    expect(result.skippedFragments).toBe(0)
    // Control: the rule after the corrupted region must keep its own context.
    expect(mustFind(result, "color")).toMatchObject({ selector: ".b", value: "#040506" })
  })
})

describe("CLI arguments", () => {
  test("--out refuses paths that resolve to the pinned input asset", () => {
    // The script documents the asset as READ-ONLY and SHA-256-pinned; letting
    // --out resolve onto it turns the audit into a destroyer of its own
    // evidence. Both the relative and absolute spelling must be refused.
    expect(() => parseArgs(["--out", ASSET_RELATIVE])).toThrow()
    expect(() => parseArgs(["--out", resolve(ROOT, ASSET_RELATIVE)])).toThrow()
  })

  test("control: --out still accepts ordinary report paths and the default", () => {
    expect(parseArgs(["--out", "reports/other-name.json"])).toBe(resolve(ROOT, "reports/other-name.json"))
    expect(parseArgs([])).toBe(resolve(ROOT, "reports/telemost_ui_color_inventory.json"))
  })
})

describe("report facts", () => {
  test("svg-dom unverified note does not misstate the number of url() paint references", async () => {
    // The note is generated output and must be factual about the asset it
    // describes. The pinned stylesheet contains six "url(" occurrences (none
    // quoted); the 7b9c09e note hardcoded "one masked url() fill".
    // Contract: if the note states a url() count, it must equal the actual
    // count; a note that states no count stays acceptable.
    const tmpOut = join(tmpdir(), `audit-colors-note-test-${process.pid}.json`)
    try {
      const proc = Bun.spawnSync([process.execPath, "run", "scripts/audit-colors.ts", "--out", tmpOut], { cwd: ROOT })
      expect(proc.exitCode).toBe(0)

      const report = JSON.parse(await readFile(tmpOut, "utf8")) as { unverified: Array<{ source: string; note: string }> }
      const note = report.unverified.find((u) => u.source === "svg-dom")?.note
      expect(note).toBeString()

      const assetCss = await readFile(resolve(ROOT, ASSET_RELATIVE), "utf8")
      const actualUrlCount = (assetCss.match(/url\(/g) ?? []).length

      const WORD_NUMBERS: Record<string, number> = { one: 1, two: 2, three: 3, four: 4, five: 5, six: 6, seven: 7, eight: 8, nine: 9, ten: 10 }
      const claim = /\b(\d+|one|two|three|four|five|six|seven|eight|nine|ten)\s+(?:[a-z-]+\s+)?url\(\)/i.exec(note ?? "")
      const statedCount = claim ? (WORD_NUMBERS[claim[1]!.toLowerCase()] ?? Number(claim[1])) : actualUrlCount
      expect(statedCount).toBe(actualUrlCount)
    } finally {
      await rm(tmpOut, { force: true })
    }
  }, 30000)
})
