/**
 * Regenerates `src/defaults/*.ts` from the JSON in `config/` and `presets/`.
 *
 * The compiled binary cannot read the repository, so the defaults it ships with
 * are baked in as TypeScript modules. Keeping two copies invites drift, so this
 * script is the only sanctioned way to update them and runs as part of `build`.
 */

import { readdir, readFile, writeFile, mkdir } from "node:fs/promises"
import { dirname, join, resolve } from "node:path"
import { fileURLToPath } from "node:url"

import { desktopThemeSchema, mappingConfigSchema, type DesktopTheme } from "../src/schema"

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..")

async function readJson(relativePath: string): Promise<unknown> {
  return JSON.parse(await readFile(resolve(ROOT, relativePath), "utf8"))
}

async function main(): Promise<void> {
  const themeRaw = await readJson("config/theme.json")
  const mappingRaw = await readJson("config/mapping.json")

  // Validate before baking: a broken default would ship inside the binary.
  const theme = desktopThemeSchema.parse(themeRaw)
  mappingConfigSchema.parse(mappingRaw)

  // Read and validate all preset files in presets/
  const presetsDir = resolve(ROOT, "presets")
  const presetEntries = await readdir(presetsDir, { withFileTypes: true })
  const presetFiles = presetEntries
    .filter((e) => e.isFile() && e.name.endsWith(".json"))
    .map((e) => e.name)
    .sort()

  const builtinPresets: Record<string, DesktopTheme> = {}

  for (const filename of presetFiles) {
    const raw = await readJson(join("presets", filename))
    const parsed = desktopThemeSchema.parse(raw)
    builtinPresets[parsed.id] = parsed
  }

  // Ensure default theme is also in presets under its id if not already
  if (!builtinPresets[theme.id]) {
    builtinPresets[theme.id] = theme
  }

  await mkdir(resolve(ROOT, "src/defaults"), { recursive: true })

  await writeFile(
    resolve(ROOT, "src/defaults/theme.ts"),
    [
      `// GENERATED by scripts/sync-defaults.ts from config/theme.json — do not edit.`,
      ``,
      `import type { z } from "zod"`,
      `import type { desktopThemeSchema } from "../schema"`,
      ``,
      `/** Written to the user's config directory on first run. */`,
      `export const DEFAULT_THEME: z.infer<typeof desktopThemeSchema> = ${JSON.stringify(theme, null, 2)}`,
      ``,
    ].join("\n"),
    "utf8",
  )

  await writeFile(
    resolve(ROOT, "src/defaults/mapping.ts"),
    [
      `// GENERATED by scripts/sync-defaults.ts from config/mapping.json — do not edit.`,
      ``,
      `import type { z } from "zod"`,
      `import type { mappingConfigSchema } from "../schema"`,
      ``,
      `/**`,
      ` * How Orb's primitive families are structured. Not a user preference, so`,
      ` * this stays compiled in rather than being written to disk.`,
      ` */`,
      `export const DEFAULT_MAPPING: z.input<typeof mappingConfigSchema> = ${JSON.stringify(mappingRaw, null, 2)}`,
      ``,
    ].join("\n"),
    "utf8",
  )

  await writeFile(
    resolve(ROOT, "src/defaults/presets.ts"),
    [
      `// GENERATED by scripts/sync-defaults.ts from presets/*.json — do not edit.`,
      ``,
      `import type { z } from "zod"`,
      `import type { desktopThemeSchema } from "../schema"`,
      ``,
      `export type DesktopTheme = z.infer<typeof desktopThemeSchema>`,
      ``,
      `/**`,
      ` * Built-in theme presets compiled into the binary.`,
      ` */`,
      `export const BUILTIN_PRESETS: Readonly<Record<string, DesktopTheme>> = ${JSON.stringify(builtinPresets, null, 2)}`,
      ``,
    ].join("\n"),
    "utf8",
  )

  console.log(
    `synced src/defaults/{theme,mapping,presets}.ts from config/ and ${Object.keys(builtinPresets).length} presets in presets/`,
  )
}

main().catch((error: unknown) => {
  process.stderr.write(`sync-defaults failed: ${error instanceof Error ? error.message : String(error)}\n`)
  process.exitCode = 1
})
